name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install golint
        run: go install golang.org/x/lint/golint

      - name: Lint and Vet Code
        run: |
          go mod download
          golint ./...
          go vet ./...

      - name: Build Docker image
        run: docker build -t ofekmoas/hii:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ofekmoas500
          password: @o782971o@

      - name: Push Docker image to Docker Hub
        run: docker push ofekmoas/hii:latest
